### ISSUE TITLE
unable to import COD1/UO

### ISSUE THREAD

**Issue by vrpixel** [mauserzjeh/cod-asset-importer#3]
Hello, I have not tried the latest version with COD2, but I re-extracted to a clean folder all PK3 from COD Deluxe (COD1+UO). When I try to open an mp map, i get this error

> Python: Traceback (most recent call last):
>   File "C:\Users\GTX1060\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\cod_asset_importer\addon\operators.py", line 24, in execute
>     importer.import_ibsp(assetpath, self.filepath)
>   File "C:\Users\GTX1060\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\cod_asset_importer\addon\importer.py", line 63, in import_ibsp
>     texture_file = tex.removeprefix(assetpath).lstrip('/\\')
> AttributeError: 'str' object has no attribute 'removeprefix'
> 
> location: <unknown location>:-1

**Comment by mauserzjeh** [comment]
Hi @vrpixel 

What blender version are you using? From the error message I assume you still use 2.92. The function **removeprefix()** is only available since python 3.9.0 so you need a blender version that is using python 3.9.0 at least. But I would advise you to use the latest blender version available.

Upgrading blender for the latest version would solve this problem.

**Comment by vrpixel** [comment]
Tried with 3.0.0, seems to import now. I'll give it some more extensive testing.
