### ISSUE TITLE
COD1UO mp_ponyri

### ISSUE THREAD

**Issue by vrpixel** [mauserzjeh/cod-asset-importer#4]
I've been having a lot of fun with the plugin, but I hit my first real error trying to open mp_ponyri .

![image](https://user-images.githubusercontent.com/46872885/176780260-bada8868-6aee-46f1-af85-813c7676fe1b.png)

I have tried many other maps, and they seemed to open just fine, although taking almost forever to load. Also noticed some missing materials, like for the vista trees on mp_foy, and also one building missing interior material on the same map.

Thanks a lot for the tool.

**Comment by mauserzjeh** [comment]
Usually modelscale is just stored as a single float. Since I haven't test all maps, it seems like some models store modelscale as 3 floats. I will soon make a fix for it.

A note on the performance. Big maps take longer to load and import as usual. I will try to further improve performance. I have seen a good example of developing python modules in rust, so when I finally will learn rust I will most likely rewrite the plugin again in rust for a much better performance.

**Comment by mauserzjeh** [comment]
I reopened it :) 
Currently I don't have anything set up to accept donations

**Comment by mauserzjeh** [comment]
The modelscale bug should be fixed now. [Check the latest release](https://github.com/mauserzjeh/cod-asset-importer/releases/latest). I tested mp_ponyri and it imported without any issues after the fix has been implemented.

**Comment by GoldenBlack4** [comment]
Hello there.
I have the same problem right now with some maps on Cod2:

```
Traceback (most recent call last):
  File "C:\Users\cedri\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\cod_asset_importer\assets\ibsp.py", line 367, in load
    self.entities = self._read_entities(file, self.version, lumps) # entities
  File "C:\Users\cedri\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\cod_asset_importer\assets\ibsp.py", line 322, in _read_entities
    angles.x = float(a[0])
ValueError: could not convert string to float: ''
[ERROR] ibsp.py:394 None
[ERROR] importer.py:40 Error loading map: C:\Users\cedri\Desktop\COD2Master\assets\maps\duhoc_assault.d3dbsp
```

Great improvement btw, thanks!
